name: rydberggpt2
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pytorch::pytorch==2.2.0
  - pytorch::torchvision>=0.15.2
  - pytorch::torchaudio>=0.7.1
  - torchdata>=0.7.1
  - numpy>=1.23
  - tensorboard>=2.12
  - matplotlib
  - jupyter 
  - tqdm
  - black
  - pandas
  - joblib
  - seaborn
  - imageio
  - pytorch-lightning>=2.2.0
  - h5py
  - pytest
  - pip
  - pip:
    - torch-tb-profiler
    - torch-summary 
    - tables 
    - torch_geometric>=2.4.0
