# 828 K params
transformer:
  num_heads: 12
  d_model: 72
  num_blocks_encoder: 4
  num_blocks_decoder: 8
  d_ff: 288 # usually 4 * d_model
  dropout: 0.1
  compile: False

graph_embedding:
  graph_num_layers: 4
  graph_hidden_dim: 512
  in_node_dim: 4 # omega delta beta Rb

training:
  strategy: "auto"
  precision: 32 # half precision saves lots of memory! 32 is default
  max_epochs: 1000
  batch_size: 500
  learning_rate: 0.001
  criterion: "NLLLoss" #KLLoss
  from_checkpoint: null
  accumulate_grad_batches: 1
  detect_anomaly: True

logger:
  log_every: 30

optimizer: 
  optimizer: "AdamW"
  t_initial: 1
  t_mult: 2
  eta_min: 0.00001

dataset:
  num_workers: 10 # for each GPU process  
  buffer_size: 50 # how many chunks of data to load into memory at once, each chunk contains 100,000 samples

rydberg:
  num_states: 2

profiler: 
  profiler: "PyTorchProfiler"
  advanced_monitoring: False
  detect_anomaly: False

misc:
  seed: 42
  prog_bar: False
