# 201 K params
transformer:
  num_heads: 10
  d_model: 40
  num_blocks_encoder: 2
  num_blocks_decoder: 6
  d_ff: 160 # usually 4 * d_model
  dropout: 0.1
  compile: False

graph_embedding:
  graph_num_layers: 2
  graph_hidden_dim: 64 
  in_node_dim: 4 # omega delta beta, blockade_radius

training:
  strategy: "auto"
  precision: 32 #16-mixed # half precision saves lots of memory! 32 is default
  max_epochs: 1000
  batch_size: 500 # set to 1000 if only single GPU 
  learning_rate: 0.001
  criterion: "NLLLoss" #KLLoss
  from_checkpoint: null
  accumulate_grad_batches: 1
  detect_anomaly: True

logger:
  log_every: 30

optimizer: 
  optimizer: "AdamW"
  t_initial: 1
  t_mult: 2
  eta_min: 0.00001

dataset:
  num_workers_per_gpu: 16
  chunks_in_memory: 50 # how many chunks of data to load into memory at once, each chunk contains 100,000 samples

rydberg:
  num_states: 2

profiler: 
  profiler: "PyTorchProfiler"
  advanced_monitoring: False

misc:
  seed: 42
  prog_bar: False
