transformer:
  num_heads: 8
  d_model: 128
  num_blocks_encoder: 2
  num_blocks_decoder: 8
  d_ff: 512 # usually 4 * d_model
  dropout: 0.1
  compile: False

graph_embedding:
  graph_num_layers: 2
  graph_hidden_dim: 128
  in_node_dim: 4 # omega delta beta Rb

training:
  strategy: "auto"
  precision: 16 # half precision saves lots of memory! 32 is default
  max_epochs: 10
  batch_size: 128
  learning_rate: 0.001
  criterion: "NLLLoss" #KLLoss
  from_checkpoint: null
  accumulate_grad_batches: 1
  detect_anomaly: True

logger:
  log_every: 30

optimizer: 
  optimizer: "AdamW"
  t_initial: 1
  t_mult: 2
  eta_min: 0.00001

dataset:
  num_atoms: null
  num_samples: null
  delta: null
  num_workers: 4

rydberg:
  num_states: 2
  num_encoder_embedding_dims: 3

profiler: 
  profiler: "PyTorchProfiler"

misc:
  seed: 8596
  prog_bar: True
