transformer:
  num_heads: 8
  d_model: 128
  num_blocks: 8
  d_ff: 512 # usually 4 * d_model
  dropout: 0.1

training:
  devices: 2
  strategy: "ddp"
  accelerator: "gpu"
  precision: 16 # half precision saves lots of memory! 32 is default
  max_epochs: 20
  batch_size: 128
  learning_rate: 0.001
  optimizer: "Adam"

dataset:
  num_atoms: null
  num_samples: null
  delta: null

rydberg:
  num_states: 2
  num_encoder_embedding_dims: 4

profiler: 
  profiler: "SimpleProfiler"

misc:
  seed: 42
  prog_bar: False