transformer:
  num_heads: 8
  d_model: 32
  num_blocks: 2
  d_ff: 128 # usually 4 * d_model
  dropout: 0.1
  compile: False

training:
  strategy: "auto"
  precision: "16-mixed" # half precision saves lots of memory! 32 is default
  max_epochs: 1000
  batch_size: 16
  learning_rate: 0.005
  optimizer: "Adam"
  criterion: "KLLoss"

dataset:
  num_atoms: null
  num_samples: null
  delta: null
  num_workers: 0
  dataset_name: dataset_small

rydberg:
  num_states: 2
  num_encoder_embedding_dims: 4

profiler: 
  profiler: "PyTorchProfiler"

misc:
  seed: 42
  prog_bar: True