transformer:
  num_heads: 8
  d_model: 32
  num_blocks: 2
  d_ff: 128 # usually 4 * d_model
  dropout: 0.1

training:
  devices: "auto"
  strategy: "auto"
  accelerator: "auto"
  precision: 16 # half precision saves lots of memory! 32 is default
  max_epochs: 10
  batch_size: 16
  learning_rate: 0.01
  optimizer: "Adam"

dataset:
  num_atoms: null
  num_samples: null
  delta: null

rydberg:
  num_states: 2
  num_encoder_embedding_dims: 4

profiler: 
  profiler: "SimpleProfiler"

misc:
  seed: 42
  prog_bar: True